### ISSUE TITLE
Buffalo LinkStation empty directory

### ISSUE THREAD

**Issue by Bravo315** [tjibbevanderlaan/chromeos-filesystem-sftp#42] opened 2015-02-23 12:58 UTC
Device: Samsung Chromebox 3
Server: Custom Buffalo LinkStation on a dynamic IP address
OS: Chrome (stable) 40.0.2214.114
Other: Device registered with a domain management licence

I can successfully launch the app and enter my FTP credentials. Upon hitting "Mount", the mountAttempt{} message appears at the bottom left and subsequently mountSucsess{} with the fingerprint.

When I open the mounted NAS LinkStation drive (with correct credentials), the directory is completely empty.

This happens when the credentials are "kept" with and without password saving and happens whether or not a root is specified.

I can confirm the SFTP credentials are correct and using SSH2. I have used multiple servers to test this out - only the LinkStation has problems with this.

Thanks for this awesome app!
Jack.

**Comment by yoichiro** [comment] 2015-02-23 23:59
@Bravo315 Hmm... Of course, I don't have the device, therefore, I can't know the detail situation you faced. Could you see the console output for the background context of this app by the DevTools? If I can get the output messages at occuring this issue, I may know the cause...

**Comment by Bravo315** [comment] 2015-03-04 15:17
Hi Yoichiro, sorry it's not parsed. I thought it would be more useful in text format rather than screenshots. Hopefully it helps.

>background.js:1344 Object {type: "mount", serverName: "192.168.1.5", serverPort: "22", authType: "password", username: "jack"…}authType: "password"mountPath: ""password: "[REMOVED]"privateKey: ""serverName: "192.168.1.5"serverPort: "22"type: "mount"username: "jack"__proto__: Object__defineGetter__: function __defineGetter__() { [native code] }__defineSetter__: function __defineSetter__() { [native code] }__lookupGetter__: function __lookupGetter__() { [native code] }__lookupSetter__: function __lookupSetter__() { [native code] }constructor: function Object() { [native code] }hasOwnProperty: function hasOwnProperty() { [native code] }isPrototypeOf: function isPrototypeOf() { [native code] }propertyIsEnumerable: function propertyIsEnumerable() { [native code] }toLocaleString: function toLocaleString() { [native code] }toString: function toString() { [native code] }valueOf: function valueOf() { [native code] }get __proto__: function __proto__() { [native code] }set __proto__: function __proto__() { [native code] background.js:177 
mountPath: 
background.js:223 
Object {message: "fingerprint", request: 0, values: Array[2]}message: "fingerprint"request: 0values: Array[2]__proto__: Object
background.js:625 Object {requestId: 0, fingerprint: "1760bb442f36d8df6b98fb637f52a7a1", algorithm: "ssh-rsa"}
background.js:1344 Object {type: "accept", requestId: "0", fileSystemId: "sftpfs://192.168.1.5:22/jack"}
background.js:635 allowToConnect
background.js:223 Object {message: "authenticated", request: 0, values: Array[0]}message: "authenticated"request: 0values: Array[0]__proto__: Object
background.js:1234 getTaskQueue: Created. sftpfs://192.168.1.5:22/jack
background.js:45 TaskQueue: addTask - Call consume task: length=1
background.js:55 TaskQueue: consumeTask - execute task: length=1
background.js:754 onGetMetadataRequested: thumbnail=false
background.js:755 Object {entryPath: "/", fileSystemId: "sftpfs://192.168.1.5:22/jack", requestId: 1, thumbnail: false}
background.js:1274 getMetadataCache: Created. sftpfs://192.168.1.5:22/jack
background.js:223 Object {message: "error", request: 0, values: Array[1]}message: "error"request: 0values: Array[1]__proto__: Object
background.js:774 NOT_FOUND
background.js:62 TaskQueue: consumeTask - queue: empty
background.js:45 TaskQueue: addTask - Call consume task: length=1
background.js:55 TaskQueue: consumeTask - execute task: length=1
background.js:754 onGetMetadataRequested: thumbnail=false
background.js:755 Object {entryPath: "/", fileSystemId: "sftpfs://192.168.1.5:22/jack", requestId: 2, thumbnail: false}
background.js:223 Object {message: "error", request: 0, values: Array[1]}message: "error"request: 0values: Array[1]__proto__: Object
background.js:774 NOT_FOUND
background.js:62 TaskQueue: consumeTask - queue: empty
background.js:45 TaskQueue: addTask - Call consume task: length=1
background.js:55 TaskQueue: consumeTask - execute task: length=1
background.js:754 onGetMetadataRequested: thumbnail=false
background.js:755 Object {entryPath: "/", fileSystemId: "sftpfs://192.168.1.5:22/jack", requestId: 3, thumbnail: false}
background.js:223 Object {message: "error", request: 0, values: Array[1]}
background.js:774 NOT_FOUND
background.js:62 TaskQueue: consumeTask - queue: empty
background.js:45 TaskQueue: addTask - Call consume task: length=1
background.js:55 TaskQueue: consumeTask - execute task: length=1
background.js:754 onGetMetadataRequested: thumbnail=false
background.js:755 Object {entryPath: "/", fileSystemId: "sftpfs://192.168.1.5:22/jack", requestId: 4, thumbnail: false}
background.js:223 Object {message: "error", request: 0, values: Array[1]}message: "error"request: 0values: Array[1]__proto__: Object
background.js:774 NOT_FOUND
background.js:62 TaskQueue: consumeTask - queue: empty
background.js:45 TaskQueue: addTask - Call consume task: length=1
background.js:55 TaskQueue: consumeTask - execute task: length=1
background.js:754 onGetMetadataRequested: thumbnail=false
background.js:755 Object {entryPath: "/", fileSystemId: "sftpfs://192.168.1.5:22/jack", requestId: 5, thumbnail: false}
background.js:223 Object {message: "error", request: 0, values: Array[1]}message: "error"request: 0values: Array[1]0: "Unable to open file with SFTP -31"length: 1__proto__: Array[0]__proto__: Object__defineGetter__: function __defineGetter__() { [native code] }__defineSetter__: function __defineSetter__() { [native code] }__lookupGetter__: function __lookupGetter__() { [native code] }__lookupSetter__: function __lookupSetter__() { [native code] }constructor: function Object() { [native code] }hasOwnProperty: function hasOwnProperty() { [native code] }isPrototypeOf: function isPrototypeOf() { [native code] }propertyIsEnumerable: function propertyIsEnumerable() { [native code] }toLocaleString: function toLocaleString() { [native code] }toString: function toString() { [native code] }valueOf: function valueOf() { [native code] }get __proto__: function __proto__() { [native code] }set __proto__: function __proto__() { [native code] }
background.js:774 NOT_FOUND
background.js:62 TaskQueue: consumeTask - queue: empty
background.js:45 TaskQueue: addTask - Call consume task: length=1
background.js:55 TaskQueue: consumeTask - execute task: length=1
background.js:726 onReadDirectoryRequested
background.js:727 Object {directoryPath: "/", fileSystemId: "sftpfs://192.168.1.5:22/jack", requestId: 7}
background.js:223 Object {message: "error", request: 0, values: Array[1]}message: "error"request: 0values: Array[1]0: "Unable to open dir with SFTP -31"length: 1__proto__: Array[0]__proto__: Object__defineGetter__: function __defineGetter__() { [native code] }__defineSetter__: function __defineSetter__() { [native code] }__lookupGetter__: function __lookupGetter__() { [native code] }__lookupSetter__: function __lookupSetter__() { [native code] }constructor: function Object() { [native code] }hasOwnProperty: function hasOwnProperty() { [native code] }isPrototypeOf: function isPrototypeOf() { [native code] }propertyIsEnumerable: function propertyIsEnumerable() { [native code] }toLocaleString: function toLocaleString() { [native code] }toString: function toString() { [native code] }valueOf: function valueOf() { [native code] }get __proto__: function __proto__() { [native code] }set __proto__: function __proto__() { [native code] }
background.js:742 Unable to open dir with SFTP -31
background.js:62 TaskQueue: consumeTask - queue: empty
background.js:45 TaskQueue: addTask - Call consume task: length=1
background.js:55 TaskQueue: consumeTask - execute task: length=1
background.js:726 onReadDirectoryRequested
background.js:727 Object {directoryPath: "/", fileSystemId: "sftpfs://192.168.1.5:22/jack", requestId: 8}
background.js:223 Object {message: "error", request: 0, values: Array[1]}message: "error"request: 0values: Array[1]__proto__: Object
background.js:742 Unable to open dir with SFTP -31
background.js:62 TaskQueue: consumeTask - queue: empty

**Comment by yoichiro** [comment] 2015-03-04 23:17
@Bravo315 Hmm... Certainly, there are some error responses. But, I cannot know the detail from the text above. I would like to know the detail of the following line:

> background.js:223 Object {message: "error", request: 0, values: Array[1]}message: "error"request: 0values: Array[1]proto: Object

The "values" property has the error message. I think that you can expand the line on the DevTools Console panel. Could you tell me the value of the "values" property?

**Comment by Bravo315** [comment] 2015-03-06 14:21
The requested value states "Unable to open file with SFTP -31" so may be an issue with how it's setup on our NAS.

In background:223.js, I found the following in object{}

1. Error in __proto__ function seem to loop infinitely
![error223js 1](https://cloud.githubusercontent.com/assets/11158154/6526584/5d96f556-c40b-11e4-830f-a09c754ed09e.png)

2. Error 2: status is set to blank
![error 223js 2](https://cloud.githubusercontent.com/assets/11158154/6526597/7fe46102-c40b-11e4-96bd-70a8383f29e9.png)

3. Error 3 contains two empty names
![error 223js 3](https://cloud.githubusercontent.com/assets/11158154/6526613/aab77f7c-c40b-11e4-821d-4540f729e2be.png)

Thanks,
Jack.

**Comment by yoichiro** [comment] 2015-03-18 02:29
@Bravo315 Hmm... The error code -31 means "Protocol mismatch". That is, this application (actually, libssh2) cannot talk with your NAS server because of some reason... Unfortunately, I don't have the NAS device, therefore, it seems that I cannot get enough information to fix this issue...

I have one more question. Could you get the output of 'ls -laF' executed on the mounted root directory?

**Comment by yoichiro** [comment] 2015-04-07 22:00
@Bravo315 Do you have same error in the latest version 1.7.3?

**Comment by fast-hedgehog** [comment] 2015-07-03 20:52
I have a buffalo linkstation, and i had similar error messages when trying to set "Path a root directory" as "Share".  Setting this as "array1/Share" resolved the issue for me.  (this is case sensitive).

**Comment by yoichiro** [comment] 2019-02-20 21:30
It seems that the specified path as a root was wrong. Close this issue.

**Closed by yoichiro** 2019-02-20 21:30 UTC
